version: "3"
services:
  loadbalancer:
    image: traefik:2.6.1
    ports:
      - "80:80"
     # - "8080:8080"
    command:
     # - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" #comment out for production
      # - "--certificatesresolvers.myresolver.acme.email=mkaleta@duck.com"
      # - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # - "./letsencrypt:/letsencrypt"

  backend:
    build: ./backend/
    image: hilbert_backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/v1`)"
      - "traefik.http.routers.backend.entrypoints=web"
      # - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api/v1"
    environment:
      - DB_CONN_STRING=mongodb://root:root@mongodb:27017

  frontend:
    build: ./frontend/
    image: hilbert_frontend
    labels:
      - "traefik.enable=true"
      # - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend-service.loadBalancer.sticky.cookie=true"
      - "traefik.http.services.frontend-service.loadBalancer.sticky.cookie.name=UjFyHvjMxzVCF48BgE0A"

  mongodb:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
    # ports:
    #   - "27017:27017"

  # mongoexpress:
  #   image: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin
  #   depends_on:
  #     - mongodb
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.mongoexpress.rule=Host(`localhost`)"
  #     - "traefik.http.routers.mongoexpress.entrypoints=mongoexpress"

volumes:
  mongodbdata:
  mongodbconfig:
