version: "3"
services:
  loadbalancer:
    build: ./load_balancer/
    image: hilbert_loadbalancer
    ports:
      - "8080:80"
      - "8001:8001"
    deploy:
      placement:
        constraints:
          - node.role == manager

  backend:
    build: ./backend/
    image: hilbert_backend

  mongodb:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
  
  # mongoexpress:
  #   image: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
  #     - ME_CONFIG_MONGODB_AUTH_USERNAME=root
  #     - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - "8888:8081"

volumes:
  mongodbdata:
  mongodbconfig: