version: "3"
services:
  loadbalancer:
    build: ./load_balancer/
    image: hilbert_loadbalancer
    ports:
      - "8080:80"
      - "8001:8001"
    deploy:
      placement:
        constraints:
          - node.role == manager

  backend:
    build: ./backend/
    image: hilbert_backend

  mongodb:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb

volumes:
  mongodbdata:
  mongodbconfig: