version: "1.0"
services:
  web:
    build: .
    ports:
      - "8000:8000"
  mongodb:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb
    ports:
      - "8001:27017"
volumes:
  mongodbdata:
  mongodbconfig: