global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'loadbalancer:8080'
  - job_name: rabbitmq
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'rabbitmq:15692'